<?php

return array_map('realpath', [
    $basePath . '/vendor/tracy/tracy/src/Tracy/Bar.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/BlueScreen.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/Debugger.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/DefaultBarPanel.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/Dumper.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/FireLogger.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/Helpers.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/IBarPanel.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/ILogger.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/Logger.php',
    $basePath . '/vendor/tracy/tracy/src/Tracy/OutputDebugger.php',

    $basePath . '/vendor/symfony/finder/SplFileInfo.php',
    $basePath . '/vendor/symfony/finder/Expression/Regex.php',
    $basePath . '/vendor/symfony/finder/Expression/ValueInterface.php',
    $basePath . '/vendor/symfony/finder/Expression/Expression.php',
    $basePath . '/vendor/symfony/finder/Iterator/FilterIterator.php',
    $basePath . '/vendor/symfony/finder/Iterator/MultiplePcreFilterIterator.php',
    $basePath . '/vendor/symfony/finder/Iterator/PathFilterIterator.php',
    $basePath . '/vendor/symfony/finder/Iterator/ExcludeDirectoryFilterIterator.php',
    $basePath . '/vendor/symfony/finder/Iterator/RecursiveDirectoryIterator.php',
    $basePath . '/vendor/symfony/finder/Iterator/FileTypeFilterIterator.php',
    $basePath . '/vendor/symfony/finder/Shell/Shell.php',
    $basePath . '/vendor/symfony/finder/Adapter/AdapterInterface.php',
    $basePath . '/vendor/symfony/finder/Adapter/AbstractAdapter.php',
    $basePath . '/vendor/symfony/finder/Adapter/AbstractFindAdapter.php',
    $basePath . '/vendor/symfony/finder/Adapter/GnuFindAdapter.php',
    $basePath . '/vendor/symfony/finder/Adapter/PhpAdapter.php',
    $basePath . '/vendor/symfony/finder/Adapter/BsdFindAdapter.php',
    $basePath . '/vendor/symfony/finder/Finder.php',

    $basePath . '/packages/orbit/machine/src/Support/helpers.php',
    $basePath . '/packages/orbit/machine/src/Application.php',
    $basePath . '/packages/orbit/machine/src/ServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/ConfigServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/CookieServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/DbServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/DispatcherServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/EventServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/FormServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/LogServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/ModelMetadataServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/RouterServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/SessionServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/UrlServiceProvider.php',
    $basePath . '/packages/orbit/machine/src/Provider/ViewServiceProvider.php',

    $basePath . '/packages/orbit/machine/src/Tracy/ConfigBar.php',
    $basePath . '/packages/orbit/machine/src/Tracy/DbBar.php',
    $basePath . '/packages/orbit/machine/src/Tracy/DefaultBar.php',
    $basePath . '/packages/orbit/machine/src/Tracy/DebugBridge.php',

    $basePath . '/packages/orbit/machine/src/Session/ConnectorInterface.php',
    $basePath . '/packages/orbit/machine/src/Session/Connector/FilesConnector.php',
    $basePath . '/packages/orbit/machine/src/Session/Connector/NullConnector.php',
    $basePath . '/packages/orbit/machine/src/Session/Connector/RedisConnector.php',
    $basePath . '/packages/orbit/machine/src/Session/Manager.php',

    $basePath . '/packages/orbit/machine/src/Auth/Auth.php',
    $basePath . '/packages/orbit/machine/src/Auth/AuthServiceProvider.php',

    $basePath . '/packages/orbit/machine/src/Support/Arr.php',
    $basePath . '/packages/orbit/machine/src/Support/Filesystem.php',
    $basePath . '/packages/orbit/machine/src/Support/Macroable.php',
    $basePath . '/packages/orbit/machine/src/Support/SecureRandom.php',
    $basePath . '/packages/orbit/machine/src/Support/Str.php',

]);